services:
  vmod-impress:
    container_name: vmod-impress
    image: vmod-impress
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    platform: linux/amd64
    user: ${USER_ID}:${GROUP_ID}
    ports: [21777:80]
    volumes:
      - .:/build:rw,cached
      - ./config:/etc/varnish:rw,cached
